### ISSUE TITLE
3D version

### ISSUE THREAD

**Issue by Pamphlett** [anguoyuan/Topological-RANSAC#1]
Hi Guoyuan,

Thanks for open-sourcing this great work!
I am wondering if the topology-based verification can be extended to 3D since I am mostly working on LiDAR data :)

**Comment by anguoyuan** [comment]
Thank you for your interest in our work. I'm also considering expanding the topological RANSAC to 3D applications. However, my expertise primarily lies in areas like matching and SfM, and I'm not yet well-versed in LiDAR data. Therefore, I'm unable to provide a specific response to your question at this moment. But I'm open to discussing the details further. Feel free to reach out via email at anguoyuan111@gmail.com, or we can arrange a Zoom meeting to explore this topic more deeply if you want.

**Comment by Pamphlett** [comment]
Hi Guoyuan, thanks! I just sent you an email. Please check out your Gmail :)
