### ISSUE TITLE
Question about setting in Table 1 of the paper

### ISSUE THREAD

**Issue by sungonce** [anguoyuan/Topological-RANSAC#2]
Hi Guoyuan.

Thanks for your interesting work.
I have a question about the setting in Table 1 of the paper.

Looking at the demo code, I got the following code result:
```
Topological RANSAC result for:   all_souls_000013.jpg all_souls_000015.jpg
detected   51 homomorphism regions in total
the number of patches in the largest homomorphism region is:   289

Topological RANSAC result for:   all_souls_000013.jpg all_souls_000027.jpg
detected   43 homomorphism regions in total
the number of patches in the largest homomorphism region is:   56

```
Here, how can I define the similarity of two images using TP?
Is the similarity between two images determined by the number of homeomorphism regions, or is there another way?
And how do we mix the initial similarity and re-ranking similarity?

For example, I have attached the DELG paper. In DELG, they define the re-ranking similarity as min(i,70)/70, where I is the number of inlier matches. They mix the initial similarity c and re-ranking similarity min(I,70)/70 with the weighted sum with the value alpha.

![Screenshot from 2024-05-08 15-53-56](https://github.com/anguoyuan/Topological-RANSAC/assets/9362019/5a47b399-6720-499d-b163-aa1805fdc50d)

A detailed description of this will significantly increase the reproducibility of your paper.
Once again, thank you very much for a great paper!

**Comment by anguoyuan** [comment]
Hi, Seongwon. Thanks for your interest in our paper. 

To determine the similarity of the two images using TP, we can use "the number of patches in the largest homomorphism region," "the size of the largest homomorphism region," or "the sum of all the homomorphism region sizes."  I do not recommend "the number of homeomorphism regions" cause it does not reflect the similarity well. 

In Table 1 of the paper, we do **not** mix the initial DELG similarity and re-ranking similarity. Table 1 is not for improving the performance of the initial ranking but for fairly evaluating different reranking techniques under challenging scenarios. We select the top 100 images using  DELG, randomize their order, and do not use DELG similarity when comparing different reranking techniques.  

Let me know if you have additional questions. And feel free to email me (anguoyuan111@gmail.com) if you want to discuss technique details or research ideas.
